service:
    resource: "@ServiceBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: "@ModelBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

base:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
